name: Deploy on PR Merge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to live branch
      run: |
        git config --global user.name 'Ibraheem Adeniyi'
        git config --global user.email 'ibonly01@gmail.com'
        git checkout -b live
        git rm -rf .
        cp -r dist/* .
        git rm -rf dist/
        git rm -rf node_modules
        git add .
        git commit -m 'Deploy to live branch'
        git push origin live --force
